################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CC_DEPS := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
BoardHardware/accel \
BoardHardware/als \
BoardHardware/buzzer \
BoardHardware/display \
BoardHardware/flash \
BoardHardware/internal \
BoardHardware/ir \
BoardHardware/led \
BoardHardware/mp3 \
BoardHardware/nRF \
BoardHardware/power \
BoardHardware/sd \
BoardHardware/temp \
BoardHardware/touch \
BoardHardware/wifi \
BoardHardware/wifi/common \
BoardHardware/wifi/simplelink/source \
Core/Src \
Core/Startup \
Drivers/STM32F7xx_HAL_Driver/Src \
FATFS/App \
FATFS/Target \
Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src \
Middlewares/ST/STM32_USB_Device_Library/Core/Src \
Middlewares/Third_Party/FatFs/src \
Middlewares/Third_Party/FatFs/src/option \
TouchGFX/App \
TouchGFX/generated/fonts/src \
TouchGFX/generated/gui_generated/src/accel_screen \
TouchGFX/generated/gui_generated/src/buzzer_screen \
TouchGFX/generated/gui_generated/src/common \
TouchGFX/generated/gui_generated/src/containers \
TouchGFX/generated/gui_generated/src/flash_screen \
TouchGFX/generated/gui_generated/src/gallery_screen \
TouchGFX/generated/gui_generated/src/light_screen \
TouchGFX/generated/gui_generated/src/main_menu_screen \
TouchGFX/generated/gui_generated/src/mp3_screen \
TouchGFX/generated/gui_generated/src/nrf_screen \
TouchGFX/generated/gui_generated/src/pwr_screen \
TouchGFX/generated/gui_generated/src/rgb_led_screen \
TouchGFX/generated/gui_generated/src/temp_screen \
TouchGFX/generated/gui_generated/src/time_screen \
TouchGFX/generated/gui_generated/src/weather_screen \
TouchGFX/generated/images/src \
TouchGFX/generated/images/src/__designer \
TouchGFX/generated/texts/src \
TouchGFX/gui/src/accel_screen \
TouchGFX/gui/src/buzzer_screen \
TouchGFX/gui/src/common \
TouchGFX/gui/src/containers \
TouchGFX/gui/src/flash_screen \
TouchGFX/gui/src/gallery_screen \
TouchGFX/gui/src/light_screen \
TouchGFX/gui/src/main_menu_screen \
TouchGFX/gui/src/model \
TouchGFX/gui/src/mp3_screen \
TouchGFX/gui/src/nrf_screen \
TouchGFX/gui/src/pwr_screen \
TouchGFX/gui/src/rgb_led_screen \
TouchGFX/gui/src/temp_screen \
TouchGFX/gui/src/time_screen \
TouchGFX/gui/src/weather_screen \
TouchGFX/target \
USB_DEVICE/App \
USB_DEVICE/Target \

