################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../BoardHardware/wifi/simplelink/source/device.c \
../BoardHardware/wifi/simplelink/source/driver.c \
../BoardHardware/wifi/simplelink/source/flowcont.c \
../BoardHardware/wifi/simplelink/source/fs.c \
../BoardHardware/wifi/simplelink/source/netapp.c \
../BoardHardware/wifi/simplelink/source/netcfg.c \
../BoardHardware/wifi/simplelink/source/nonos.c \
../BoardHardware/wifi/simplelink/source/socket.c \
../BoardHardware/wifi/simplelink/source/spawn.c \
../BoardHardware/wifi/simplelink/source/wlan.c 

OBJS += \
./BoardHardware/wifi/simplelink/source/device.o \
./BoardHardware/wifi/simplelink/source/driver.o \
./BoardHardware/wifi/simplelink/source/flowcont.o \
./BoardHardware/wifi/simplelink/source/fs.o \
./BoardHardware/wifi/simplelink/source/netapp.o \
./BoardHardware/wifi/simplelink/source/netcfg.o \
./BoardHardware/wifi/simplelink/source/nonos.o \
./BoardHardware/wifi/simplelink/source/socket.o \
./BoardHardware/wifi/simplelink/source/spawn.o \
./BoardHardware/wifi/simplelink/source/wlan.o 

C_DEPS += \
./BoardHardware/wifi/simplelink/source/device.d \
./BoardHardware/wifi/simplelink/source/driver.d \
./BoardHardware/wifi/simplelink/source/flowcont.d \
./BoardHardware/wifi/simplelink/source/fs.d \
./BoardHardware/wifi/simplelink/source/netapp.d \
./BoardHardware/wifi/simplelink/source/netcfg.d \
./BoardHardware/wifi/simplelink/source/nonos.d \
./BoardHardware/wifi/simplelink/source/socket.d \
./BoardHardware/wifi/simplelink/source/spawn.d \
./BoardHardware/wifi/simplelink/source/wlan.d 


# Each subdirectory must supply rules for building sources it contributes
BoardHardware/wifi/simplelink/source/device.o: ../BoardHardware/wifi/simplelink/source/device.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -DDEBUG -c -I../TouchGFX/gui/include -I../FATFS/App -I../TouchGFX/generated/fonts/include -I../USB_DEVICE/Target -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TouchGFX/generated/texts/include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../TouchGFX/generated/images/include -I../Middlewares/ST/touchgfx/framework/include -I../BoardHardware -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../TouchGFX/target/generated -I../Drivers/CMSIS/Include -I../Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../USB_DEVICE/App -I../TouchGFX/generated/gui_generated/include -I../FATFS/Target -I../TouchGFX/App -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../TouchGFX/target -I../Middlewares/Third_Party/FatFs/src -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"BoardHardware/wifi/simplelink/source/device.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
BoardHardware/wifi/simplelink/source/driver.o: ../BoardHardware/wifi/simplelink/source/driver.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -DDEBUG -c -I../TouchGFX/gui/include -I../FATFS/App -I../TouchGFX/generated/fonts/include -I../USB_DEVICE/Target -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TouchGFX/generated/texts/include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../TouchGFX/generated/images/include -I../Middlewares/ST/touchgfx/framework/include -I../BoardHardware -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../TouchGFX/target/generated -I../Drivers/CMSIS/Include -I../Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../USB_DEVICE/App -I../TouchGFX/generated/gui_generated/include -I../FATFS/Target -I../TouchGFX/App -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../TouchGFX/target -I../Middlewares/Third_Party/FatFs/src -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"BoardHardware/wifi/simplelink/source/driver.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
BoardHardware/wifi/simplelink/source/flowcont.o: ../BoardHardware/wifi/simplelink/source/flowcont.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -DDEBUG -c -I../TouchGFX/gui/include -I../FATFS/App -I../TouchGFX/generated/fonts/include -I../USB_DEVICE/Target -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TouchGFX/generated/texts/include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../TouchGFX/generated/images/include -I../Middlewares/ST/touchgfx/framework/include -I../BoardHardware -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../TouchGFX/target/generated -I../Drivers/CMSIS/Include -I../Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../USB_DEVICE/App -I../TouchGFX/generated/gui_generated/include -I../FATFS/Target -I../TouchGFX/App -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../TouchGFX/target -I../Middlewares/Third_Party/FatFs/src -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"BoardHardware/wifi/simplelink/source/flowcont.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
BoardHardware/wifi/simplelink/source/fs.o: ../BoardHardware/wifi/simplelink/source/fs.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -DDEBUG -c -I../TouchGFX/gui/include -I../FATFS/App -I../TouchGFX/generated/fonts/include -I../USB_DEVICE/Target -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TouchGFX/generated/texts/include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../TouchGFX/generated/images/include -I../Middlewares/ST/touchgfx/framework/include -I../BoardHardware -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../TouchGFX/target/generated -I../Drivers/CMSIS/Include -I../Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../USB_DEVICE/App -I../TouchGFX/generated/gui_generated/include -I../FATFS/Target -I../TouchGFX/App -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../TouchGFX/target -I../Middlewares/Third_Party/FatFs/src -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"BoardHardware/wifi/simplelink/source/fs.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
BoardHardware/wifi/simplelink/source/netapp.o: ../BoardHardware/wifi/simplelink/source/netapp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -DDEBUG -c -I../TouchGFX/gui/include -I../FATFS/App -I../TouchGFX/generated/fonts/include -I../USB_DEVICE/Target -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TouchGFX/generated/texts/include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../TouchGFX/generated/images/include -I../Middlewares/ST/touchgfx/framework/include -I../BoardHardware -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../TouchGFX/target/generated -I../Drivers/CMSIS/Include -I../Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../USB_DEVICE/App -I../TouchGFX/generated/gui_generated/include -I../FATFS/Target -I../TouchGFX/App -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../TouchGFX/target -I../Middlewares/Third_Party/FatFs/src -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"BoardHardware/wifi/simplelink/source/netapp.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
BoardHardware/wifi/simplelink/source/netcfg.o: ../BoardHardware/wifi/simplelink/source/netcfg.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -DDEBUG -c -I../TouchGFX/gui/include -I../FATFS/App -I../TouchGFX/generated/fonts/include -I../USB_DEVICE/Target -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TouchGFX/generated/texts/include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../TouchGFX/generated/images/include -I../Middlewares/ST/touchgfx/framework/include -I../BoardHardware -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../TouchGFX/target/generated -I../Drivers/CMSIS/Include -I../Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../USB_DEVICE/App -I../TouchGFX/generated/gui_generated/include -I../FATFS/Target -I../TouchGFX/App -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../TouchGFX/target -I../Middlewares/Third_Party/FatFs/src -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"BoardHardware/wifi/simplelink/source/netcfg.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
BoardHardware/wifi/simplelink/source/nonos.o: ../BoardHardware/wifi/simplelink/source/nonos.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -DDEBUG -c -I../TouchGFX/gui/include -I../FATFS/App -I../TouchGFX/generated/fonts/include -I../USB_DEVICE/Target -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TouchGFX/generated/texts/include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../TouchGFX/generated/images/include -I../Middlewares/ST/touchgfx/framework/include -I../BoardHardware -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../TouchGFX/target/generated -I../Drivers/CMSIS/Include -I../Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../USB_DEVICE/App -I../TouchGFX/generated/gui_generated/include -I../FATFS/Target -I../TouchGFX/App -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../TouchGFX/target -I../Middlewares/Third_Party/FatFs/src -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"BoardHardware/wifi/simplelink/source/nonos.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
BoardHardware/wifi/simplelink/source/socket.o: ../BoardHardware/wifi/simplelink/source/socket.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -DDEBUG -c -I../TouchGFX/gui/include -I../FATFS/App -I../TouchGFX/generated/fonts/include -I../USB_DEVICE/Target -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TouchGFX/generated/texts/include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../TouchGFX/generated/images/include -I../Middlewares/ST/touchgfx/framework/include -I../BoardHardware -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../TouchGFX/target/generated -I../Drivers/CMSIS/Include -I../Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../USB_DEVICE/App -I../TouchGFX/generated/gui_generated/include -I../FATFS/Target -I../TouchGFX/App -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../TouchGFX/target -I../Middlewares/Third_Party/FatFs/src -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"BoardHardware/wifi/simplelink/source/socket.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
BoardHardware/wifi/simplelink/source/spawn.o: ../BoardHardware/wifi/simplelink/source/spawn.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -DDEBUG -c -I../TouchGFX/gui/include -I../FATFS/App -I../TouchGFX/generated/fonts/include -I../USB_DEVICE/Target -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TouchGFX/generated/texts/include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../TouchGFX/generated/images/include -I../Middlewares/ST/touchgfx/framework/include -I../BoardHardware -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../TouchGFX/target/generated -I../Drivers/CMSIS/Include -I../Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../USB_DEVICE/App -I../TouchGFX/generated/gui_generated/include -I../FATFS/Target -I../TouchGFX/App -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../TouchGFX/target -I../Middlewares/Third_Party/FatFs/src -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"BoardHardware/wifi/simplelink/source/spawn.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
BoardHardware/wifi/simplelink/source/wlan.o: ../BoardHardware/wifi/simplelink/source/wlan.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F767xx -DDEBUG -c -I../TouchGFX/gui/include -I../FATFS/App -I../TouchGFX/generated/fonts/include -I../USB_DEVICE/Target -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TouchGFX/generated/texts/include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../TouchGFX/generated/images/include -I../Middlewares/ST/touchgfx/framework/include -I../BoardHardware -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../TouchGFX/target/generated -I../Drivers/CMSIS/Include -I../Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../USB_DEVICE/App -I../TouchGFX/generated/gui_generated/include -I../FATFS/Target -I../TouchGFX/App -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../TouchGFX/target -I../Middlewares/Third_Party/FatFs/src -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"BoardHardware/wifi/simplelink/source/wlan.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

